# Generated by Django 5.0.7 on 2024-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro8_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='students', to='pro8_app.project'),
        ),
    ]
